---
  dependency:
    name: galaxy
  
  driver:
    name: podman
  
  platforms:
    - name: debstretch
      image: geerlingguy/docker-debian9-ansible
      pre_build_image: true
      volumes:
        - /sys/fs/cgroup:/sys/fs/cgroup:ro
      capabilities:
        - SYS_ADMIN
      published_ports:
        - 0.0.0.0:8081:80/tcp
    - name: centos8
      image: jgeusebroek/centos8-molecule
      pre_build_image: true
      tmpfs:
        - /run
        - /tmp
      volumes:
        - /sys/fs/cgroup:/sys/fs/cgroup:ro
      capabilities:
        - SYS_ADMIN
      command: "/usr/sbin/init"
      published_ports:
        - 0.0.0.0:8080:80/tcp
  
  provisioner:
    name: ansible
    log: true
  
  verifier:
    name: goss
  
  lint: |
    ansible-lint .
    yamllint .

  scenario:
    name: default
    test_sequence:
      - lint
      - destroy
      # - dependency
      - syntax
      - create
      # - prepare
      - converge
      - idempotence
      # - side_effect
      #- verify
      #- destroy 
